baseURL: "https://lives.rocks"
languageCode: en-us
title: Safe-Zone
theme: PaperMod

params:
  homeInfoParams:
    Title: "é¾™è¡”æµ·ç ï¼Œæ¸¸é±¼ä¸é¡¾
    \n\n\n
     
    "
    Content: "Welcome to my blog. Everything about tech, daily life, and fun.
    \n\n\n
    \n\n\n
    \n\n\n
    æœ¬åšå®¢æ˜¯é˜¿æ¯çš„æ–‡å­—è‡ªç•™åœ°ï¼Œåˆ†ç±»ä¸ºæŠ€æœ¯éšæ„Ÿï¼Œæ—¥å¸¸çç¢ï¼Œå †æ–‡ä»“åº“ï¼Œæ¬¢è¿æ¥ç©è€çš„å„ä½ğŸ‘
    "

  socialIcons:
    - name: email
      url:
    - name: twitter
      url: "https://twitter.com"
    - name: qq
      url:

  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  comments: true
  ShowReadingTime: true
  ShowCodeCopyButtons: true
  cover:
    linkFullImages: true
    responsiveImages: true

menu:
  main:
    - identifier: categories
      name: åˆ†ç±»-Categories 
      url: /categories/
      weight: 10
    - identifier: tags
      name: æ ‡ç­¾-Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: å½’æ¡£-Archive
      url: /archives/
      weight: 30
    - identifier: search
      name: æœç´¢-Search
      url: /search/
      weight: 40

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
